### ISSUE TITLE
Loading a folder loads routes inside it automatically

### ISSUE THREAD

**Issue by onemoreahmad** [lorisleiva/lody#8]
Hi, using Laravel, when I load a folder with Lody, routes inside that folder get registered without explicitly registering them myself.    
 I don't know if it's intended or I'm missing something.

 
```
// in AppServiceProvider
Lody::classes('Modules')->each(function ($classname) {
   // nothing is here .. 
});
```
 
Create "Modules" folder in the root of a Laravel project 
and inside it I would create Auth/routes.php file

```
Route::get('test', function () {
    return 'route from Auth/routes.php';
});
```

and then "autoload" Modules folder in composer 

```
"autoload": {
    "psr-4": {
        ..
        "Modules\\": "Modules/",
        ..
    }
},
```
now, strange enough , all routes inside (routes.php) get registered automatically,
if I `php artisan route:list`, I'll see test route get listed. 
 
but if I did everything without `Lody::classes('Modules')...` no routes get registered.

**Comment by lorisleiva** [comment]
Hi there,👋

I think that's expected, right?

In order to load the classes, you need to load the files. Even just to know if a file contains a class, you need to load its content.

Routes files are not wrapped in any classes or functions so their execution is not deferred meaning they run as soon as they are loaded.

I'd recommend using some of the filters provided by Lody to exclude these routes files explicitly if that's the expected behaviour.

**Comment by onemoreahmad** [comment]
You're right, I think yes it's expected, for now I'm enjoying the free loading for the routes 😁 In most of my modules I do need the routes anyway, so I'll just keep it that way for now, thanks for your quick reply, appreciated  🙏
